// SPDX-License-Identifier: MIT
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
const root = fileURLToPath(new URL('../', import.meta.url));
const hash = data => createHash('sha256').update(data).digest('hex');
const deps = JSON.parse(await readFile(resolve(root, 'docs/dependency-manifest.json')));
for (const file of deps) if (hash(await readFile(resolve(root, file.path))) !== file.sha256) throw new Error(`Dependency changed: ${file.path}`);
const recordDeps=JSON.parse(await readFile(resolve(root,'docs/record-dependency-manifest.json')));
for(const file of recordDeps)if(hash(await readFile(resolve(root,file.path)))!==file.sha256)throw new Error(`Record dependency changed: ${file.path}`);
const recordFiles=recordDeps.filter(f=>f.path.startsWith('optional/')).map(({path,bytes,sha256})=>({path,bytes,sha256}));
if(recordFiles.reduce((n,f)=>n+f.bytes,0)>32*1024*1024)throw new Error('Optional pack exceeds 32MiB');
const recordPack={version:hash(JSON.stringify(recordFiles)).slice(0,16),files:recordFiles};
await writeFile(resolve(root,'src/optional-assets.js'),`// SPDX-License-Identifier: MIT\n// Generated by tools/audit-files.js.\nexport const OPTIONAL_PACK = ${JSON.stringify(recordPack,null,2)};\n`);
await writeFile(resolve(root,'optional-manifest.js'),`// SPDX-License-Identifier: MIT\n// Generated by tools/audit-files.js.\nself.DOPA_OPTIONAL = ${JSON.stringify(recordPack,null,2)};\n`);
const licenses = JSON.parse(await readFile(resolve(root,'docs/license-sources.json')));
for (const file of licenses) if (hash(await readFile(resolve(root,file.path))) !== file.sha256) throw new Error(`License changed: ${file.path}`);
const paths = ['index.html', 'style.css', 'privacy.html', 'manifest.webmanifest', 'LICENSE', 'PRIVACY.md', 'THIRD_PARTY_NOTICES.md','optional-manifest.js'];
async function walk(dir) { for (const file of await readdir(resolve(root, dir), {withFileTypes:true})) { const path = `${dir}/${file.name}`; if (file.isDirectory()) await walk(path); else paths.push(path); } }
for (const dir of ['src','assets','vendor','models','licenses']) await walk(dir);
const files = [];
for (const path of paths.sort()) { const data = await readFile(resolve(root, path)); files.push({path, bytes:data.byteLength, sha256:hash(data)}); }
const version = hash(JSON.stringify(files) + hash(await readFile(resolve(root,'sw.js')))).slice(0,16);
await writeFile(resolve(root,'cache-manifest.js'), `// SPDX-License-Identifier: MIT\n// Generated by tools/audit-files.js. Do not edit by hand.\nself.DOPA_CACHE = ${JSON.stringify({version, files}, null, 2)};\n`);
await writeFile(resolve(root,'docs/distribution-manifest.json'), `${JSON.stringify({version, files},null,2)}\n`);
console.log(`Verified ${deps.length} core and ${recordDeps.length} record dependency hashes; release ${version}; ${files.length} cached files, ${files.reduce((n,f)=>n+f.bytes,0).toLocaleString()} bytes.`);
