// SPDX-License-Identifier: MIT
export const messages = {
  recordOptions:['顔を隠す・動画を作る','Face Mask & video options'],
  videoUpdateWait:['動画を仕上げてから更新できます','Finish the video before updating'],
  recordIntro:['好きなだけ運動したら、あなたが主役の動画に。','Move as long as you like. Your session becomes your story.'],maskLabel:['顔をDopa Maskで隠す','Cover my face with Dopa Mask'],recordLabel:['Dopa Record ON · 終了後に自動編集','Dopa Record ON · edited after you finish'],backgroundLabel:['背景','Background'],roomNotice:['部屋が動画に映ります。','Your room will appear in the video.'],blurNotice:['背景をぼかします。部屋を完全に隠す機能ではありません。','Softens your background; it does not completely hide your room.'],stageNotice:['背景をDopaの舞台に置き換えます。','Replaces your background with the Dopa stage.'],previewScene:['カメラで見え方を確認','Preview with camera'],previewStop:['プレビューを閉じる','Close preview'],maskPreparing:['マスクを準備しています…','Preparing your mask…'],maskUnavailable:['マスクを表示できないため、映像を隠しています。運動は続けられます。','Camera view is hidden while the mask is unavailable. You can keep moving.'],recordError:['RECORD · 一時停止中','RECORD · temporarily unavailable'],recordLimited:['RECORD ON · 素材を整理中','RECORD ON · managing clips'],videoFinishing:['運動の成長をまとめています… {n}%','Putting your story together… {n}%'],videoRealtime:['動画を再生しながら仕上げています… {n}%','Finishing through playback… {n}%'],videoReady:['その回の成長が、一本の作品になりました。','Your session has become your own story.'],videoEmpty:['今回は使える映像が足りませんでした。運動の成果は保存されています。','Not enough usable footage this time. Your workout results are kept.'],videoFailed:['動画を仕上げられませんでした。運動の成果はそのままです。','Could not finish the video. Your workout results are kept.'],videoSave:['動画を保存 ↓','Save video ↓'],videoShare:['動画をシェア ↗','Share video ↗'],videoRetry:['もう一度仕上げる','Retry finishing'],recordLocal:['素材は端末内だけで処理。次の運動を始めると一時素材を破棄します。','Clips stay on your device and are discarded when you start another session.'],

  calibrationDetails:['説明・設定','Help & settings'],
  maskRetrying:['マスクを再接続しています。手の動きは表示されます。','Reconnecting the mask. Your hand movements remain visible.'],
  maskFindFace:['顔がカメラに入るよう、少し離れてね。手の動きは表示されます。','Step back until your face is in view. Your hand movements remain visible.'],
  maskStepBack:['顔に近すぎるようです。少し離れると映像が戻ります。','Your face is too close. Step back to restore the camera view.'],
  maskOnePerson:['ひとりでカメラに映ってね。確認中はアバターで表示します。','Keep one person in view. An avatar appears while checking.'],
  maskTracking:['顔を確認中です。手の動きはアバターで表示します。','Checking your face. An avatar shows your hand movements.'],
  maskBackground:['背景を確認中です。手の動きはアバターで表示します。','Checking the background. An avatar shows your hand movements.'],
  practiceLeft:['まずは左の光へ！どちらの手でもOK · あと{n}秒','Try the left glow! Either hand works · {n}s'],practiceRight:['いいね！次は右の光へ · あと{n}秒','Nice! Now touch the right glow · {n}s'],practiceSkip:['練習をスキップ →','Skip practice →'],rise:['{name}へ… ビートをためよう！','Get ready for {name}…'],
  cardBuild:['BUILD THE BEAT','BUILD THE BEAT'],cardTitle:['あなたが育てたビート','THE BEAT YOU BUILT'],cardDemo:['カメラなしのデモの成果','No-camera demo results'],cardSession:['身体の動きが、音と光になった。','Your movement became music and light.'],cardFever:['最高FEVER','HIGHEST FEVER'],cardTime:['運動時間','ACTIVE TIME'],cardThanks:['いい動き！またビートを育てよう。','Nice moves. Let’s build another beat.'],cardPositive:['ひと息ついても、成果はあなたのもの。','Every move counts. Your progress stays yours.'],cardSave:['成果カードを画像で保存 ↓','Save result card ↓'],cardSaved:['画像の保存を開始しました。','Image download started.'],cardFailed:['保存できませんでした。もう一度試してください。','Could not save. Please try again.'],playAgain:['もう一回、動こう ↗','Move again ↗'],
  history:['運動の記録','Your sessions'], hero:['動くたび、世界がちょっと\n気持ちよくなる。','A little movement.\nA lot of joy.'],
  description:['あなたの動きが、音になって、光になって。\nスマホを置いたら、あとは楽しく手を伸ばすだけ。','Your movement becomes music and light.\nSet up your phone and reach for the glowing targets.'],
  mode:['遊び方','Play mode'], upper:['半身 · 近くでリーチ','Upper body · reach nearby'], full:['全身 · ステップも楽しむ','Full body · reach and step'],
  start:['動いてはじめる ↗','START MOVING ↗'], demo:['カメラなしで試す →','Try without a camera →'],
  privacyShort:['◈ 映像・姿勢は端末内で処理。Record ONのときだけ動画素材を一時収録。外部へ送信しません。','◈ Processed on your device. Video clips are collected only with Record ON. Never uploaded.'],
  step1Title:['手を伸ばす。','Reach out.'],step1:['スマホを立てて、光るターゲットにタッチ。\n身体がそのままコントローラーに。','Stand your phone upright and touch glowing targets.\nYour body is the controller.'],
  step2Title:['ビートが育つ。','Build the beat.'],step2:['動くほど楽器と光が増えていく。\n自分のペースで音楽をつくろう。','Movement adds instruments and light.\nMake music at your own pace.'],
  step3Title:['いいことだけ。','Good vibes only.'],step3:['MISSも減点も、ゲームオーバーもなし。\nひと息ついても、成果はそのまま。','No MISS, penalties or game over.\nTake a break: your progress stays.'],
  setupTitle:['スマホを立てる。半身でも、全身でも。','Stand your phone upright. Upper or full body.'],setup:['ひとりで、無理のない範囲で。初めてのときはカメラの許可が必要です。','Play solo, within a comfortable reach. Allow the camera when you first start.'],
  course:['3分コース','3-minute flow'],privacy:['プライバシー','Privacy'],licenses:['ライセンス','Licenses'],resume:['再開する →','Resume →'],
  demoBadge:['カメラなしのデモ · GOへドラッグ／タップ','No-camera demo · drag / tap GO'],pause:['一時停止','Pause'],soundAlert:['音を有効に ♪','Enable sound ♪'],
  settingsTitle:['ひと息、設定。','Take a breather.'],settingsIntro:['ENERGYはそのまま。準備できたら、また動こう。','Your ENERGY stays. Move again when you’re ready.'],
  audioHelp:['確認音が聞こえないときは、端末の音量・消音設定も確認してください。','If you cannot hear the test tone, check your device volume and silent mode.'],reach:['動く範囲','Reach'],wide:['広く動く','Wide reach'],small:['その場で小さく','Compact reach'],cameraFit:['カメラ表示','Camera view'],cover:['画面いっぱい','Fill screen'],contain:['広く映す','Show more'],volume:['音量','Volume'],reduced:['演出ひかえめ','Gentler effects'],
  videoPrivate:['◈ Record素材は端末内だけで処理','◈ Record clips stay on your device'],pwaTip:['iPhoneはSafariの共有から「ホーム画面に追加」して、追加したアイコンから開くと、ブラウザのバーがない広い画面で遊べます。','On iPhone, use Safari’s Share → Add to Home Screen, then open the icon for a larger view without browser bars.'],again:['また動こう →','Let’s move again →'],finish:['運動を終了する','Finish session'],
  resultTitle:['いい動きでした！','Nice moves!'],resultIntro:['あなたの動きで、音楽が育ちました。','Your movement made the music grow.'],resultClose:['もうひと息、また動こう →','Take a breath, then move again →'],clearHistory:['記録を削除','Delete history'],close:['閉じる','Close'],diagnostics:['端末内の診断','On-device diagnostics'],updateNotice:['新しいバージョンがあります。','A new version is ready.'],update:['運動を終えて更新','Finish and update'],updateBusy:['ほかのタブの運動を終えて更新','Finish sessions in other tabs to update'],
  hintUpper:['半身で：近くで立っても、座っても。両手を胸の前へ。距離は画角に合わせて調整。','Upper body: stand nearby or sit. Show both hands in front of your chest. Adjust distance to your camera view.'],hintFull:['全身で：腰まで映る距離へ。ステップ・上下動も楽しめます。','Full body: move back until your hips are visible. Enjoy steps and up-and-down movement too.'],
  soundOn:['音 ON','Sound ON'],soundOff:['音 OFF','Sound OFF'],audioPending:['確認音を準備中…','Preparing test tone…'],audioQuiet:['音はOFFです','Sound is off'],audioReady:['音が聞こえないときは →','Cannot hear the sound? →'],audioEnable:['タップして音を有効に →','Tap to enable sound →'],audioTest:['音を試す','Test sound'],audioRetry:['音を有効にする','Enable sound'],
  startingDemo:['音を準備しています','Preparing sound'],starting:['カメラを許可してね\n音と姿勢推定を準備しています','Allow the camera\nPreparing sound and motion tracking'],preparing:['準備しています','Getting ready'],paused:['ひと息つこう\nENERGYはそのまま','Take a breath\nYour ENERGY stays'],
  cameraDenied:['カメラが許可されていません。\nブラウザのサイト設定で許可して、再開してください','Camera permission is needed.\nAllow it in your browser’s site settings, then resume.'],cameraMissing:['カメラが見つかりません。別の端末でも試せます','No camera found. Try another device.'],cameraBusy:['カメラが使用中のようです。ほかのアプリを閉じて再開してください','Your camera may be in use. Close other camera apps, then resume.'],cameraError:['カメラを起動できません。再開して試してください','Could not start the camera. Resume to try again.'],error:['準備できませんでした。再開して試してください','Could not get ready. Resume to try again.'],
  calibrationTitle:['カメラに身体を見せよう','Let the camera see you'],calibrationUpper:['両手を胸の前へ。立っても座ってもOK。','Show both hands in front of your chest. Standing or sitting is fine.'],calibrationFull:['肩・両手・腰が見える位置まで下がろう。','Move back until your shoulders, both hands and hips are visible.'],outlineTip:['シルエットは姿勢の例。ぴったり合わせなくてOK。','The outline is an example. You don’t need to match it exactly.'],shoulders:['肩','Shoulders'],hands:['両手を見せる','Show both hands'],hips:['腰','Hips'],detected:['確認OK','Seen'],waiting:['確認中','Looking'],holdProgress:['そのまま少し待つ','Hold briefly'],
  calShoulders:['肩と両手が映る位置に立ってね','Show your shoulders and both hands.'],calCenter:['身体を画面の中央へ','Move toward the center of the screen.'],calCloser:['もう少し近づいてね','Move a little closer.'],calHeight:['肩が画面内に入る高さへ調整してね','Tilt your phone so your shoulders are in view.'],calHips:['全身モード：腰まで映る位置へ\n近くで遊ぶなら「半身モード」へ','Full body: move back to show your hips.\nChoose Upper body to play nearby.'],calHands:['両手を一度、画面に見せてね','Show each hand to the camera once.'],calHold:['その位置で、少しだけ待ってね','Stay there for a moment.'],calReady:['準備OK！','Ready!'],countdownTip:['数字が終わったら、光るターゲットへ。どちらの手でもOK！','When the countdown ends, reach for glowing targets. Either hand works!'],demoGuide:['GOへ触れて、音をつくろう','Touch GO to make music.'],trackingUpper:['両手を胸の前へ、身体を中央へ','Show hands in front of your chest and center your body.'],trackingFull:['肩と両手を画面に戻してね','Bring your shoulders and hands back into view.'],
  calm:['ひと息','Breathe'],next:['次は{name}','Next: {name}'],until:['{name}まであと {n}','{n} to {name}'],reached:['到達済み','Reached'],upcoming:['これから','Up next'],unlocked:['解放済み','Unlocked'],locked:['未解放','Locked'],touch:['タッチ','Touch'],
  savedDemo:['カメラなしのデモとして、この端末に記録しました。','Saved on this device as a no-camera demo.'],saved:['この端末にだけ記録しました。','Saved only on this device.'],notSavedMode:['今回の成果です。このモードでは履歴を保存しません。','Here is your progress. This mode does not save history.'],notSaved:['今回の成果です。記録の保存はできませんでした。','Here is your progress. History could not be saved.'],emptyHistory:['まだ記録はありません。最初のひと動きから。','No sessions yet. Your first move starts it all.'],demoName:['デモ','Demo'],offlineReady:['オフライン利用OK','Offline ready · OK'],online:['オンライン','Online'],offlineNone:['オフライン保存なし','Offline storage unavailable'],
  unlockNote:['{name} が仲間入り','{name} joins the beat'],rallyNote:['いい動き！音がどんどん育ってる','Nice moves! Your beat keeps growing.'],feverNote:['音と光が、もう一段育った！','Your music and light just levelled up!'],feverMax:['最高のビート！','Your biggest beat!'],restNote:['ひと息ついても、成果はそのまま','Take a breath. Your progress stays.'],
  fullCue0:['左右へ、ゆっくりリーチ','Reach gently left and right'],fullCue1:['両手を上げてみよう','Try raising both hands'],fullCue2:['左右へステップ','Step left and right'],fullCue3:['ゆっくり上下に動こう','Move gently up and down'],fullCue4:['好きな動きで音をつくろう','Make music with your own moves'],fullCue5:['ひと息、のんびり動こう','Breathe and move gently'],upperCue0:['胸の前で、左右へリーチ','Reach left and right in front of your chest'],upperCue1:['両手で上のターゲットへ','Reach for the upper targets'],upperCue2:['斜めへ、交互にリーチ','Alternate diagonal reaches'],upperCue3:['小さく手を振ってみよう','Try a small wave'],upperCue4:['好きな動きで音をつくろう','Make music with your own moves'],upperCue5:['ひと息、のんびり動こう','Breathe and move gently'],
  homeLabel:['Dopa Fit ホーム','Dopa Fit home'],mascotLabel:['Dopa Fitの応援マスコット','Dopa Fit cheering mascot'],mascotAlt:['丸いミント色の応援ロボット','Round mint-green cheering robot'],howLabel:['遊び方','How to play'],playLabel:['運動画面','Play screen'],canvasLabel:['ターゲットと手の周辺判定','Targets and hand touch areas'],pauseLabel:['一時停止と設定','Pause and settings'],layersLabel:['音楽のレイヤー','Music layers'],feverLabel:['FEVERの到達段階','FEVER progress'],
  privacyTitle:['あなたの映像は、\nあなたの端末の中に。','Your camera video\nstays on your device.'],cameraUseTitle:['カメラの使い方','Camera use'],cameraUse:['インカメラ映像から、ブラウザ内のMoveNetが肩・手首・腰を推定します。骨格・一時画像は端末内だけで処理します。Record ONでは顔を隠した合成映像とゲーム音を一時収録し、運動終了後に動画を作ります。自動送信はしません。半身ではカメラ全体、全身の画面いっぱい表示では可視範囲から推定します。マイクは要求せず、一時停止・終了・タブを離れたときはカメラを停止します。','MoveNet estimates shoulders, wrists and hips inside your browser. Pose data stays in memory. With Record ON, masked video and game audio are collected temporarily on your device and edited after you finish. Nothing is uploaded automatically. Upper-body mode uses the full camera image; full-body fill-screen mode uses the visible crop. No microphone is requested. Pausing, finishing or leaving the tab stops the camera.'],networkTitle:['必要な通信','Network requests'],network:['アプリ・画像・推論ライブラリ・モデルをこのサイトと同じ配信元から取得します。利用統計や外部分析SDKは使いません。ホスティング事業者は通常のアクセス処理でIPアドレス等を扱うことがあります。','The app, images, inference libraries and model load from this site’s origin. We use no usage analytics or external analytics SDKs. The hosting provider may process IP addresses during normal access.'],localTitle:['端末内の記録','On-device storage'],local:['言語・音量・演出・動く範囲・カメラ表示・半身／全身の設定と、直近30回の日時・時間・HIT数・ENERGY・最高FEVERをlocalStorageに保存します。座標や画像を履歴には保存しません。Face Maskと背景の設定も端末内に保存し、Recordの一時素材は次の運動で破棄します。成果カードは集計とマスコットだけで端末内生成し、保存操作でPNGをダウンロードします。「運動の記録」で履歴を削除できます。ブラウザのサイトデータ削除で設定とキャッシュも消せます。','localStorage holds language, volume, effects, reach, camera view and body mode settings, plus the latest 30 session summaries (date, duration, HIT count, ENERGY and highest FEVER). Coordinates are not saved to history. Record clips stay in session memory only, until the next workout. Face Mask and background preferences are saved locally. Result cards use only totals and mascot art; the Save button downloads a locally generated PNG. Delete history in Your sessions; clear browser site data to remove settings and caches.'],offlineTitle:['オフライン','Offline use'],offlineText:['Service Workerはアプリとモデルなどの静的ファイルだけをキャッシュします。すべて保存できた後に利用可能と表示し、運動中に更新版を強制適用しません。','The Service Worker caches only static files such as the app and model. Offline ready appears after all required files are saved. Updates are never forced during play.'],privacyDetails:['詳しいPrivacy文書（日本語）','Detailed privacy document (Japanese)'],thirdParty:['第三者ライセンス','Third-party licenses'],back:['Dopa Fitに戻る →','Back to Dopa Fit →']
};
let language='ja';
export const getLanguage=()=>language;
export function initialLanguage(saved,languages=globalThis.navigator?.languages||['ja']) { return ['ja','en'].includes(saved)?saved:languages[0]?.toLowerCase().startsWith('ja')?'ja':'en'; }
export function setLanguage(value) { language=value==='en'?'en':'ja';return language; }
export function t(key,values={},locale=language) { const text=messages[key]?.[locale==='en'?1:0]??key;return text.replace(/\{(\w+)\}/g,(_,name)=>String(values[name]??`{${name}}`)); }
export function applyLanguage(root=document) {
  root.documentElement?.setAttribute('lang',language);
  for(const el of root.querySelectorAll('[data-i18n]'))el.textContent=t(el.dataset.i18n);
  for(const [data,attribute] of [['data-i18n-label','aria-label'],['data-i18n-alt','alt']])for(const el of root.querySelectorAll(`[${data}]`))el.setAttribute(attribute,t(el.getAttribute(data)));
  for(const el of root.querySelectorAll('[data-language]'))el.value=language;
}
